### ISSUE TITLE
package.json little problem

### ISSUE THREAD

**Issue by DarkBeardRUS** [songzh96/homebridge-crestron#1]
Please add lines

  "engines": {
    "homebridge": ">=0.4.16",
    "node": ">=0.12.0"
  },
  "dependencies": {
    "async": "^2.6.0",
    "request": "^2.88.0"
  },
  "keywords": [
    "homebridge-plugin",
    "homebridge",
    "crestron"
  ],

to package.json
Otherwise homebridge it does not start

**Comment by songzh96** [comment]
Thanks,I will fix it
