### ISSUE TITLE
multiple devices not indexing

### ISSUE THREAD

**Issue by michaelblock42** [songzh96/homebridge-crestron#11]
this works fantastic if I only use one device of each type.  The index is showing up in the log as "undeclared", so no matter how many devices are available, all control points at the first one.  Am I doing something wrong?

**Comment by songzh96** [comment]
Hi @michaelblock42 
I don't understand what you mean.
can you put some pictures?

You can also refer to it, config-sample.json

**Comment by michaelblock42** [comment]
Hi,

here is a picture of my config and log.  I have been unable to figure out how to get the ID value to Crestron so that the proper device can be parsed.
<img width="302" alt="Screen Shot 2021-01-31 at 1 03 39 PM" src="https://user-images.githubusercontent.com/4577556/106397926-c54f9900-63c4-11eb-9b44-a55fbfd66654.png">

As you can see from the log below, the device with ID = 1 shows up as "undefined".
<img width="687" alt="Screen Shot 2021-01-31 at 1 02 14 PM" src="https://user-images.githubusercontent.com/4577556/106397899-9b967200-63c4-11eb-8e5d-43dc986a0c33.png">

This is keeping the S+ parser from working properly.  What am I doing wrong?

**Comment by songzh96** [comment]
try use "id" not "ID"

**Comment by michaelblock42** [comment]
that fixed it. thanks!
