### ISSUE TITLE
No feedback from Homebridge

### ISSUE THREAD

**Issue by pmakar** [songzh96/homebridge-crestron#13]
Hi, I'm using DMPS3 processor and I have run into some issues.

- homebridge sends toggle info to crestron and only on power on so it's not possible to know when switch is actually turned off
- SwitchOff functions are not working.

But thanks a lot for your development, integration with homekit would be impossible without you.

Thank you,

Petar

**Comment by songzh96** [comment]
Hi Petar

you need link switch feedback. please use the "Set/Reset" Function to create a virtual feedback

**Comment by pmakar** [comment]
You mean using 2 switches 1 for power on and second for power off?

**Comment by pmakar** [comment]
Aaah! Sorry, figured it out. Thank you for your help.

Petar
