### ISSUE TITLE
Configure alarm

### ISSUE THREAD

**Issue by carlosveny** [songzh96/homebridge-crestron#14]
I don't see an option to configure an alarm in the creskit plugin. However, in the documentation of this plugin it says it supports alarms.
Any help?
This is the list of accessories types available in the plugin:
![imagen](https://user-images.githubusercontent.com/58152614/147773478-edf09d45-0d46-4e12-a8ce-43f7005fb930.png)

**Comment by carlosveny** [comment]
Actually, this is using the homebridge UI plugin but I can configure it manually writing in the json. If you can post an example of the configuration of an alarm or a garage door I will be thankfull. Also, in the SIMPL library I don't see the option to configure alarms or garage doors.
Any help would be appreciate it,
Carlos

**Comment by songzh96** [comment]
soory，I've been busy recently. I'll fix it when I'm free
Best Regards
songzh


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "songzh96/homebridge-crestron"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月1日(星期六) 晚上11:51
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [songzh96/homebridge-crestron] Configure alarm (Issue #14)





 
Actually, this is using the homebridge UI plugin but I can configure it manually writing in the json. If you can post an example of the configuration of an alarm or a garage door I will be thankfull. Also, in the SIMPL library I don't see the option to configure alarms or garage doors.
 Any help would be appreciate it,
 Carlos
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
