### ISSUE TITLE
type as a name

### ISSUE THREAD

**Issue by DarkBeardRUS** [songzh96/homebridge-crestron#2]
Hi,
I use
Configuration UI plugin for Homebridge
homebridge-config-ui-x v3.9.6
In the homebridge interface, I see the device type as a name, but I don’t see the name.

**Comment by songzh96** [comment]
Sorry，I have never used homebridge-config-ui.
So I can't answer you for the time being.

**Comment by DarkBeardRUS** [comment]
Excuse me, maybe my phrases seem rude, but this is because of a poor knowledge of English.

**Comment by songzh96** [comment]
hhh,Me too.
I will test homebridge-config-ui  when I have time.

**Comment by songzh96** [comment]
Hi @DarkBeardRUS .
I just used homebridge-config-u-x , I also didn't see the name.
But if you right click the accessories,you will find the name.
i think the bug is not ma plugin.may be the  homebridge-config-ui The extracted characters don't match my plugin
