### ISSUE TITLE
Modification of the module for Athom Homey

### ISSUE THREAD

**Issue by DarkBeardRUS** [songzh96/homebridge-crestron#3]
Can you remake the module for Athom Homey? I am ready to participate financially. Since the programmer of me is bad.

**Comment by songzh96** [comment]
Вы имеете в виду использование Athom Homey для управления устройствами Crestron?

**Comment by DarkBeardRUS** [comment]
Yes

**Comment by songzh96** [comment]
Я взглянул на информацию Хоми, и это был хороший продукт.
Кроме того, на GitHub есть программы, которые позволяют Crestron подключаться к Homey.
Однако в настоящее время у меня еще много работы, нет времени учиться, кроме того, Homey не слишком популярен в Китае, я могу купить его в Китае без соответствующего оборудования, а затем протестировать.
стесняться
