### ISSUE TITLE
Please remove password from Simpl+ module

### ISSUE THREAD

**Issue by ddetton** [songzh96/homebridge-crestron#5]
Thanks for putting this crestron homebridge package together.  Since you have this posted publicly on github, you should probably remove the password protection from the Simpl+ module.  Most people will need to open it up to adjust array sizing to accomodate their needs.  Most experienced Crestron programmers know how to crack the encryption so having the password on there wastes the 5 minutes that it takes to crack it.  And those that don't know how to crack it, won't be able to use your package.  Thanks!

**Comment by songzh96** [comment]
Hi @ddetton 

First, you can use homebridge-creskit package, That has no password.
also, you can use homebridge-crestron-simpl and HBCrestron

Second, you can crack it.

Best Regards
Songzh

**Comment by gongdingfeng** [comment]
How to crack password
