### ISSUE TITLE
Simpl+ DimLightbulb - No need to set light state

### ISSUE THREAD

**Issue by ddetton** [songzh96/homebridge-crestron#6]
The code inside the CmdParser function in the Simpl+ module that handles the setLightBrightness command on the DimLightbulb service does not need to set the light state before setting the dim level.  The lighting systems that I work with: Crestron, Lutron, and Vantage, do not need a separate command to set light state before setting the level.  The code in the repo looks for a value of 999 then sets the dim level to 100%, then later sets the desired dim level for the light.  All this does is cause the light to briefly go to 100% before going to the desired dim level.  I just changed my code to look like this:

	if (Service="DimLightbulb" && Cmd="setLightBrightness") {
	         returnvalue = ValueInt;
		 if (returnvalue >= 0) { 
		 	if(returnvalue = 999) {
		 		// Do not need to set light state when adjusting levels.
		 	}
		 	else {
		 		DimLight_Set[IDInt] = returnvalue * 65535 / 100; //0 off, 1-100
		 	}			
		}
	}

**Comment by songzh96** [comment]
Hi @ddetton ,

This is a problem with HomeKit. When you swipe, an open command is sent. In order to filter this command, you need to use 999.

If you delete the code you said, you will not be able to use Siri to turn on the lights (for example: Siri, please help me turn on the lights), you must say "Siri, please help me turn the light to 50%"

**Comment by ddetton** [comment]
You're right, my code broke the "Hey Siri, turn the room lights on" command.  I just changed to code to send a lights_on command instead of setting the level to 65535.  I do this because I use a default level for the on command that can be something less than 100%.  Seldom do I ever want my lights at 100%.  Thanks for the explanation.  You can close this out.
