### ISSUE TITLE
Not compiled correctly 

### ISSUE THREAD

**Issue by jredbart** [songzh96/homebridge-crestron#7]
Hi there,
I have tried to add this module to my Crestron program however it has not been complied correctly and therefore does not appear in SIMPL windows. I then tried to recompile the SIMPL+ module only to see that it had been password protected. 

Please can you either recompile the module and then re-upload it or share the password with me so I can compile it my self. 

Thank you,
Joshi

**Comment by songzh96** [comment]
please use demo program
