### ISSUE TITLE
Add the number of control outputs

### ISSUE THREAD

**Issue by Kaveckiy** [songzh96/homebridge-crestron#8]
Hi!

How can I add the number of control outputs in Crestron Module?

**Comment by songzh96** [comment]
This is a free trial version and you cannot add it.

Best Regards
Songzh

**Comment by Kaveckiy** [comment]
Can You show me when I can Add number of control inputs and outputs.

I can't edit module - it password protected.

**Comment by songzh96** [comment]
Sorry，If you need me to custom development, please send me an email. Developing this plugin also takes a lot of time, time is money, please understand.

**Comment by Kaveckiy** [comment]
I can edit module itself if it evailable.

And I want make donate for great module, please write You e-mail.

**Comment by songzh96** [comment]
songzh1996@gmail.com
