### ISSUE TITLE
using this with homeassistant?

### ISSUE THREAD

**Issue by Magew** [songzh96/homebridge-crestron#9]
Hi songz96,

Not sure if this is the appropriate place to message you, but could this possibly be used or ported over to homeassistant?

**Comment by songzh96** [comment]
Hi

Not yet Now


I have also been preparing to develop plug-ins for homeassisant, but due to work reasons, I have no time to develop
But you can use node-red-crestron and node-red-home assistant to integrate&nbsp;


Best Regards&nbsp;
Songzh


------------------ Original ------------------
